"""Canonical contracts for ReDevOps runtime interoperability.

0.3.x consolidates the runtimes onto ONE universal protocol identity. Two layers:

  * `runtime_contracts.canonical` — the strict Decimal canonical: `content_hash`
    over `canonical_json`, floats refused, `rcv1:` digests. This is the identity
    every runtime must reproduce byte-for-byte, in any language.
  * `runtime_contracts.protocol` — the seal semantics over that canonical: the
    domain-facing `seal_hash` / `content_hash` that apply one explicit number
    policy (floats quantized to a fixed scale) so domain payloads carrying floats
    can be hashed without re-introducing cross-language float ambiguity.

The top-level `content_hash` exported here is the **domain-facing** one (seal
policy); the strict, float-refusing form is `canonical.content_hash`
(re-exported as `strict_content_hash`). `runtime_contracts.models` carries domain
vocabulary and layers on top of the protocol, never the other way round.
"""
from .canonical import (
    CANONICALIZATION_VERSION,
    CONTRACT_VERSION,
    CanonicalizationError,
    canonical_json,
    canonicalize,
    decimal_string,
)
from .canonical import content_hash as strict_content_hash
from .protocol import (
    SEAL_CONTRACT_VERSION,
    SEAL_NUMBER_PLACES,
    canonical_form,
    content_hash,
    prepare,
    seal_hash,
    EvidenceRef,
    EvidenceChange,
    ControlEvidence,
    ControlEvidenceCollector,
    ControlStatus,
    RuntimeStream,
    InteractionEvent,
    ConversationRef,
    MediaArtifact,
    TranscriptArtifact,
    SpeechSegment,
    SpeakerRef,
    ChannelRef,
    DeliveryReceipt,
    InteractionConfidence,
    Channel,
    Modality,
    ChannelAdapter,
    VoiceSessionProvider,
    SpeechProvider,
    CREATED,
    UPDATED,
    DELETED,
    KNOWN_REF_TYPES,
    RelationKind,
    MemberRole,
    LineageMember,
    Relation,
    member,
    relation,
    derived_from,
    supersedes,
    TopologyKind,
    JoinPolicy,
    ConcurrencyGroup,
    TelemetryKind,
    SecurityEventType,
    GovernanceDisposition,
    RuntimeSecurityEvent,
    SecurityTrajectory,
    correlate,
    causal_order_events,
    ContainmentState,
    Containment,
    ContainmentRefused,
    CausalCycle,
    SecurityVerdict,
    ContextIdentity,
    SecurityDecision,
    PrincipalRef,
    AuthorityContext,
    DelegationRefused,
    verify_chain,
    CredentialGrant,
    redact,
    lease_decision,
    SecretRef,
    SecretDescriptor,
    SecretMaterial,
    SECRET_CLASSIFICATIONS,
    CredentialRequirement,
    CredentialRequest,
    CredentialLease,
    LeaseStatus,
    SecretStore,
    CredentialBroker,
    KeyService,
    DenyReason,
    authorize_request,
    admit_credentials,
    TraceContext,
    span_of,
    GeoRef,
    SpatialOp,
    geometry_hash,
    GEOMETRY_PRECISION,
    validate_evidence,
    check_injection,
    check_self_granted_authority,
    check_hidden_instructions,
    check_source_spoofing,
    check_poisoned_tool_metadata,
    check_classification_escalation,
    check_cross_source_contradiction,
)
from .models import *  # noqa: F401,F403,E402
from .models import __all__ as _model_all  # noqa: E402
from .store import (  # noqa: E402
    EvidenceStore,
    EvidenceEnvelope,
    EVIDENCE_FAMILIES,
    project as project_evidence,
    FileEvidenceStore,
    InMemoryEvidenceStore,
    open_store,
    register_backend,
    available_backends,
)
from .secrets_local import (  # noqa: E402
    EnvironmentSecretStore,
    FileSecretStore,
    LocalCredentialBroker,
    CredentialDenied,
    SecretAccessError,
    open_secret_store,
    open_broker,
    register_secret_store,
    register_broker,
    available_secret_stores,
    available_brokers,
)
from .world import (  # noqa: E402
    WorldEvent,
    EntityRef,
    EntityKind,
    GroundTruth,
    RealismClass,
    IdentityGraph,
    WorldDescriptor,
    WorldRegistry,
    default_registry,
    BusinessBlock,
    Capsule,
    MilestoneKind,
    NeedsYouReason,
    TraceMilestone,
    VisualTrace,
)

__version__ = "0.3.3"
__all__ = [
    # strict canonical identity
    "CANONICALIZATION_VERSION", "CONTRACT_VERSION", "CanonicalizationError",
    "canonical_json", "canonicalize", "decimal_string", "strict_content_hash",
    # domain-facing seal (the protocol layer)
    "seal_hash", "content_hash", "canonical_form", "prepare",
    "SEAL_CONTRACT_VERSION", "SEAL_NUMBER_PLACES",
    # evidence-native protocol primitives
    "EvidenceRef", "EvidenceChange", "CREATED", "UPDATED", "DELETED", "KNOWN_REF_TYPES",
    "ControlEvidence", "ControlEvidenceCollector", "ControlStatus", "RuntimeStream",
    "InteractionEvent", "ConversationRef", "MediaArtifact", "TranscriptArtifact",
    "SpeechSegment", "SpeakerRef", "ChannelRef", "DeliveryReceipt", "InteractionConfidence",
    "Channel", "Modality", "ChannelAdapter", "VoiceSessionProvider", "SpeechProvider",
    "RelationKind", "MemberRole", "LineageMember", "Relation",
    "member", "relation", "derived_from", "supersedes",
    "TopologyKind", "JoinPolicy", "ConcurrencyGroup",
    "TelemetryKind", "SecurityEventType", "GovernanceDisposition", "RuntimeSecurityEvent", "SecurityTrajectory", "correlate", "causal_order_events", "ContainmentState", "Containment", "ContainmentRefused", "CausalCycle",
    "SecurityVerdict", "ContextIdentity", "SecurityDecision", "PrincipalRef", "AuthorityContext",
    "DelegationRefused", "verify_chain",
    "CredentialGrant", "redact", "lease_decision",
    "TraceContext", "span_of",
    "GeoRef", "SpatialOp", "geometry_hash", "GEOMETRY_PRECISION",
    "validate_evidence", "check_injection", "check_self_granted_authority",
    "check_hidden_instructions", "check_source_spoofing", "check_poisoned_tool_metadata",
    "check_classification_escalation", "check_cross_source_contradiction",
    # historical evidence plane — storage seam (open interface + reference floor + backend registry)
    "EvidenceStore", "EvidenceEnvelope", "EVIDENCE_FAMILIES", "project_evidence",
    "FileEvidenceStore", "InMemoryEvidenceStore",
    "open_store", "register_backend", "available_backends",
    # secret references + credential brokerage (contracts) and the AGPL local providers/broker
    "SecretRef", "SecretDescriptor", "SecretMaterial", "SECRET_CLASSIFICATIONS",
    "CredentialRequirement", "CredentialRequest", "CredentialLease", "LeaseStatus",
    "SecretStore", "CredentialBroker", "KeyService", "DenyReason",
    "authorize_request", "admit_credentials",
    "EnvironmentSecretStore", "FileSecretStore", "LocalCredentialBroker",
    "CredentialDenied", "SecretAccessError",
    "open_secret_store", "open_broker", "register_secret_store", "register_broker",
    "available_secret_stores", "available_brokers",
    # dataset worlds — canonical entry contract (WorldEvent, identity graph, registry, visual trace)
    "WorldEvent", "EntityRef", "EntityKind", "GroundTruth", "RealismClass",
    "IdentityGraph", "WorldDescriptor", "WorldRegistry", "default_registry",
    "BusinessBlock", "Capsule", "MilestoneKind", "NeedsYouReason", "TraceMilestone", "VisualTrace",
    *_model_all,
]
